services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/db
    ports:
      - 8000:8000
  worker:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: ["poetry", "run", "python3", "main.py", "--worker"]
    environment:
      POSTGRES_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_BASE: http://localhost:8000
    ports:
      - 5000:5000
