services:
  postgres:
    image: postgres:17.2
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data