"""Added names

Revision ID: 18935fe5c959
Revises: 5cb5cd47dc7c
Create Date: 2024-12-18 02:39:03.125055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18935fe5c959'
down_revision: Union[str, None] = '5cb5cd47dc7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('floors', 'updated_at')
    op.drop_column('floors', 'created_at')
    op.add_column('walls', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('walls', 'updated_at')
    op.drop_column('walls', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('walls', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('walls', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('walls', 'name')
    op.add_column('floors', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('floors', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('floors', 'name')
    # ### end Alembic commands ###
