"""Added walls and floors

Revision ID: 5cb5cd47dc7c
Revises:
Create Date: 2024-12-18 01:55:10.439635

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cb5cd47dc7c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "floors",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "floor_type",
            sa.Enum("linoleum", "laminate", "paint", "ceramic", name="floortype"),
            nullable=False,
        ),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("photo", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_floors")),
    )
    op.create_table(
        "walls",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "wall_type",
            sa.Enum("wallpaper", "paint", "ceramic", name="walltype"),
            nullable=False,
        ),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("photo", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("uid", name=op.f("pk_walls")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("walls")
    op.drop_table("floors")
    # ### end Alembic commands ###
